#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
  if [ -x /usr/sbin/apparmor_parser ] && [ ! -e /etc/apparmor.d/podman-desktop ]; then
    apparmor_parser -R podman-desktop 2>/dev/null || true
  fi
fi
